flyway.url=jdbc:postgresql://host.docker.internal:5432/prescreen
flyway.user=postgres
flyway.password=postgres
flyway.defaultSchema=auth
flyway.schemas=auth
flyway.locations=filesystem:auth/sql
flyway.table=flyway_history_auth
