flyway.url=jdbc:postgresql://host.docker.internal:5432/prescreen
flyway.user=postgres
flyway.password=postgres
flyway.defaultSchema=resume
flyway.schemas=resume
flyway.locations=filesystem:resume/sql
flyway.table=flyway_history_resume
